use_frameworks!

platform :ios, '8.0'

target 'ComponentModuleACategory_Example' do
  pod 'ComponentModuleACategory', :path => '../'

  target 'ComponentModuleACategory_Tests' do
    inherit! :search_paths

    
  end
end
